//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignments.PersonDetails.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignments.PersonDetails.Domain.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have entered a wrong Birth Date. Please Provide a right one.
        /// </summary>
        public static string DOBtooMuchinPast {
            get {
                return ResourceManager.GetString("DOBtooMuchinPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$&quot;.
        /// </summary>
        public static string EmailRegex {
            get {
                return ResourceManager.GetString("EmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot provide more than 49% of salary as additional pay. Please check your value..
        /// </summary>
        public static string ExcessiveAdditionalPay {
            get {
                return ResourceManager.GetString("ExcessiveAdditionalPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth seems to be from the future. P;ease provide an appropriate Date of Birth..
        /// </summary>
        public static string FutureDOB {
            get {
                return ResourceManager.GetString("FutureDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount due is less then the requested retireval amount.
        /// </summary>
        public static string InsufficientAmount {
            get {
                return ResourceManager.GetString("InsufficientAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id should be of the format ex_am.ple@example.com/in/co.in.
        /// </summary>
        public static string InvalidEmailId {
            get {
                return ResourceManager.GetString("InvalidEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a first name  without any special characters or numbers.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a last name  without any special characters or numbers.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be empty.
        /// </summary>
        public static string MissingDOB {
            get {
                return ResourceManager.GetString("MissingDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id cannot be empty.
        /// </summary>
        public static string MissingEmailId {
            get {
                return ResourceManager.GetString("MissingEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty.
        /// </summary>
        public static string MissingFirstName {
            get {
                return ResourceManager.GetString("MissingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty.
        /// </summary>
        public static string MissingLastName {
            get {
                return ResourceManager.GetString("MissingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^[\p{L} \.\&apos;\-]+$&quot;.
        /// </summary>
        public static string NameRegex {
            get {
                return ResourceManager.GetString("NameRegex", resourceCulture);
            }
        }
    }
}
